SOURCE_IMAGE = os.getenv("SOURCE_IMAGE", default='<SOURCE_IMAGE>/where-for-dinner-api-gateway-source')
LOCAL_PATH = os.getenv("LOCAL_PATH", default='.')
NAMESPACE = os.getenv("NAMESPACE", default='<NAMESPACE>')

k8s_custom_deploy(
    'where-for-dinner',
    apply_cmd="tanzu apps workload apply -f config/<WORKLOAD_YAML> --update-strategy replace --debug --live-update" +
        " --local-path " + LOCAL_PATH +
        " --source-image " + SOURCE_IMAGE +
        " --namespace " + NAMESPACE +
        " --yes >/dev/null" +
        " && kubectl get workload where-for-dinner --namespace " + NAMESPACE + " -o yaml",
    delete_cmd="tanzu apps workload delete -f config/<WORKLOAD_YAML> --namespace " + NAMESPACE + " --yes" ,
    deps=['pom.xml', './target/classes'],
    container_selector='workload',
    live_update=[
        sync('./target/classes', '/workspace/BOOT-INF/classes')
    ]
)

k8s_resource('where-for-dinner', port_forwards=["<PORT>:8080"],
    extra_pod_selectors=[{'carto.run/workload-name': 'where-for-dinner', 'app.kubernetes.io/component': 'run'}])
