apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: where-for-dinner
spec:
  virtualhost:
    fqdn: wfd.perfect300rock.com
  routes:
    - services:
      - name: where-for-dinner-api-gateway
        port: 80
