apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  annotations:
    rabbitmq.com/topology-allowed-namespaces: '*'
  name: rmq-where-for-dinner
  namespace: service-instances
spec:
  replicas: 1
  imagePullSecrets:
  - name: tanzunet-creds

