name: Update File
on:
  workflow_dispatch:
jobs:
  runMultipleCommands:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
     - run: |
        commit=$(date +%s)
        echo $commit
